tosca_definitions_version: alien_dsl_2_0_0

metadata:
  template_name: org.ystia.yorc.samples.kube.grafana
  template_version: 1.0.0-SNAPSHOT
  template_author: Yorc team

imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - docker-types:2.1.0-SM6

description: Grafana and graphite containers that can be deployed on K8S

repositories:
  docker:
    url: https://hub.docker.com/
    type: docker

node_types:
  org.ystia.yorc.samples.kube.containers.nodes.Graphite:
    derived_from: tosca.nodes.Container.Application.DockerContainer
    metadata:
      icon: images/graphite.png
    capabilities:
      http_endpoint:
        type: org.ystia.yorc.samples.kube.containers.capabilities.Graphite
        description: Endpoint to graphite Web UI
      data_collection:
        type: org.ystia.yorc.samples.kube.containers.capabilities.GraphiteDataCollectionEndpoint
        description: Endpoint to collect data
    interfaces:
      Standard:
        create:
          implementation:
            file: sitespeedio/graphite
            repository: docker
            type: tosca.artifacts.Deployment.Image.Container.Docker

  org.ystia.yorc.samples.kube.containers.nodes.Grafana:
    derived_from: tosca.nodes.Container.Application.DockerContainer
    metadata:
      icon: images/grafana.png
    capabilities:
      http_endpoint:
        type: org.ystia.yorc.samples.kube.containers.capabilities.Grafana
        description: Endpoint to visualize grafana collected data
    requirements:
      - http_endpoint:
          capability: org.ystia.yorc.samples.kube.containers.capabilities.Graphite
          relationship: tosca.relationships.ConnectsTo
          occurrences: [0, UNBOUNDED]
    interfaces:
      Standard:
        create:
          inputs:
            ENV_GRAPHITE_URL: { concat: ["http://", get_attribute: [TARGET, http_endpoint, ip_address], ":", get_attribute: [TARGET, http_endpoint, port]] }
            ENV_GF_AUTH_ANONYMOUS_ENABLED: true
          implementation:
            file: laurentg/grafana
            repository: docker
            type: tosca.artifacts.Deployment.Image.Container.Docker


capability_types:
  org.ystia.yorc.samples.kube.containers.capabilities.Graphite:
    derived_from: tosca.capabilities.Endpoint
    properties:
      docker_bridge_port_mapping:
        type: integer
        description: Port used to bridge to the container's endpoint.
        default: 8080
      port:
        type: integer
        default: 80

  org.ystia.yorc.samples.kube.containers.capabilities.GraphiteDataCollectionEndpoint:
    derived_from: tosca.capabilities.Endpoint
    properties:
      docker_bridge_port_mapping:
        type: integer
        description: Port used to bridge to the container's endpoint.
        default: 2003
      port:
        type: integer
        default: 2003


  org.ystia.yorc.samples.kube.containers.capabilities.Grafana:
    derived_from: tosca.capabilities.Endpoint
    properties:
      docker_bridge_port_mapping:
        type: integer
        description: Port used to bridge to the container's endpoint.
        default: 3000
      port:
        type: integer
        default: 3000
