#
# Copyright 2018 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Uninstall Yorc
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Disable Yorc Systemd Service
      systemd:
        name: yorc
        daemon_reload: no
        enabled: no
        state: stopped

    - name: Uninstall Yorc systemd unit
      file: 
        path: "/etc/systemd/system/yorc.service"
        state: "absent"

    - name: Cleanup Systemd Service
      systemd:
        daemon_reload: yes

    - name: Delete data dir
      file:
        path: "{{DATA_DIR}}"
        state: absent

    - name: Delete config dir
      file:
        path: "{{CONFIG_DIR}}"
        state: absent

    - name: delete Yorc user
      user:
        name: yorc
        state: absent
   
    - name: delete Yorc group
      group: 
        name: yorc
        state: absent
